### ISSUE TITLE
"Abbreviations" section title from "Z.100-201811-AnnF1" is not rendering well

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-itu#34]
The "Abbreviations" section title name is not rendered well when is nested in appendix environment. 
[ab-issue.zip](https://github.com/metanorma/metanorma-itu/files/3679456/ab-issue.zip)

**Comment by opoudjis** [comment]
Has been fixed in #39

**Comment by manuel489** [comment]
Hi @opoudjis, I'm affraid that the bug persists. When the appendix enviroment is present, both "Bibliographical references" and "Abbreviations" section titles get malformed.

[Malformed sections issue.zip](https://github.com/metanorma/metanorma-itu/files/3763381/Malformed.sections.issue.zip)

**Comment by manuel489** [comment]
Hi @opoudjis, I'm affraid that the bug persists. When the appendix enviroment is present, both "Bibliographical references" and "Abbreviations" section titles get malformed.

[Malformed sections issue.zip](https://github.com/metanorma/metanorma-itu/files/3763384/Malformed.sections.issue.zip)

**Comment by opoudjis** [comment]
Had failed to recurse in annexes the presence of references and definitions. Fixed.
